### ISSUE TITLE
bug log

### ISSUE THREAD

**Issue by SZsea** [LoneWindG/OctopathTraveler-SaveDataEditor#1]
2023/4/23 0:18:25
System.Collections.Generic.KeyNotFoundException: The given key 'SaveDate_Hour' was not present in the dictionary.
   at OctopathTraveler.BasicData..ctor() in D:\Projects\Git Projects\OctopathTraveler-SaveDataEditor\OctopathTraveler\BasicData.cs:line 64
   at OctopathTraveler.DataContext..ctor() in D:\Projects\Git Projects\OctopathTraveler-SaveDataEditor\OctopathTraveler\DataContext.cs:line 28
   at OctopathTraveler.MainWindow.Init() in D:\Projects\Git Projects\OctopathTraveler-SaveDataEditor\OctopathTraveler\MainWindow.xaml.cs:line 138
   at OctopathTraveler.MainWindow.Load(Boolean force) in D:\Projects\Git Projects\OctopathTraveler-SaveDataEditor\OctopathTraveler\MainWindow.xaml.cs:line 148
   at OctopathTraveler.MainWindow.MenuItemFileOpen_Click(Object sender, RoutedEventArgs e) in D:\Projects\Git Projects\OctopathTraveler-SaveDataEditor\OctopathTraveler\MainWindow.xaml.cs:line 41
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by LoneWindG** [comment]
自己的仓库默认好像没issue邮件通知, 才看到这个;
这个应该是0点保存的存档, 游戏存档节省大小就没往存档写入保存日期的小时时间, 导致没读到报错了; 已进行修复
